apiVersion: v1
kind: Service
metadata:
  name: todo-notification
  labels:
    app: todo-notification
spec:
  type: ClusterIP
  selector:
    app: todo-notification
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
