apiVersion: v1
kind: Service
metadata:
  name: todo-recurring
  labels:
    app: todo-recurring
spec:
  type: ClusterIP
  selector:
    app: todo-recurring
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
